### ISSUE TITLE
Feedback on names

### ISSUE THREAD

**Issue by kostya-sh** [ericlagergren/decimal#1]
I have only looked at the docs so far. My initial feedback is on naming. I think some types/methods could be named better. This is quite subjective of course but I will try to explain my choices.
- `decimal.Decimal`. Is one decimal in the type name not enough? I think `decimal.Number` or `decimal.Big` would be a better name. This also leaves the possibility to add fixed precision decimal types to this packge using names such as `decimal.Single`, `decimal.Double`, `decimal.Quad`).
- `DefaultPrecision` and `MaxPrec`/`MinPrec` are not consistently named.
- Variable names for pre-defined contexts (such as `decimal.Decimal32`) could be better named. How?
- `RoundingMode`. Maybe you can use `math/big.RoundingMode` or at least the same names?
- `NewFromXXX` methods. Maybe you can follow `big.Float` more closely and provide `SetXX` methods instead? E.g.: https://golang.org/pkg/math/big/#Int.SetString. In general I think following `big.Float` is a good idea as it makes the package easier to learn.
- `Scientific`. Better call it `ScientificString` or just `String`. I will provide more feedback on to/from string conversion later.

This list is not complete. I will add more comments later.

**Comment by ericlagergren** [comment]
> decimal.Decimal. Is one decimal in the type name not enough? I think decimal.Number or...

I do like the idea of having multiple decimal types. (Decimal32 and friends would be a _lot_ faster than the current implementation, although it'd sacrifice some accuracy.) I think I could move this to a `math` repo and have `Decimal`, `Decimal128`, etc types.

> DefaultPrecision

~~Will change, yes.~~

Done.

> Decimal32 naming

It's from IEEE 754 decimal types... I'm not sure how to rename them since it's nearly verbatim from the spec. Although, if I follow your advice and rename plus introduce a few new types I might as well rename them. I'm stumped, though.

> NewFrom...

Yeah, that's what I was thinking. Like something else in one of these issues, I think it's an artifact from the original fork which I subsequently gutted.

> RoundingMode

Good point... although one thing I don't care for is (when I'm using a non-std library) is to have to import other libraries to use it.

For instance, if I `import "x"` I dislike when I also need to `import "z"` _just_ to use x. But, it'd be trivial to rename them.

> Scientific

I'm thinking about making the default `String` be scientific because it'd save a _ton_ of space on large scales. I know Java has `plainString` and `engineeringstring` or something to that effect.

**Comment by kostya-sh** [comment]
> I think I could move this to a math repo and have Decimal, Decimal128, etc types.

While it might happen in the future I doubt that you will be able to move the code exactly as it is without any changes and API clean up. Having a package with nice names that can be used with all versions of Go now is more important IMHO.

> Decimal32 naming

Not sure about good names either. But will think about it.

> string conversions

See #5

**Comment by ericlagergren** [comment]
I think I have accomplished most, if not all, of these :)
