### ISSUE TITLE
Precision and Scale is lost

### ISSUE THREAD

**Issue by shannoncolavita** [ericlagergren/decimal#106]
I have read through the closed issues and it seems as though this should keep the scale to 2 but it doesn't. Please advise if I am missing something

		`It("loses precision", func() {
			ctx := decimal.Context{
				OperatingMode: decimal.Go,
				Precision: 3,
				MinScale: 2,
			}
			x, _ := decimal.WithContext(ctx).SetString("6.00")
			y, _ := decimal.WithContext(ctx).SetString("3.00")
			x.Quo(x, y)
			Expect(x.String()).To(Equal("2.00"))
		})`

**Comment by ericlagergren** [comment]
Unfortunately, that's not the behavior the GDA spec requires.

> The ideal (simplest) exponent for the result of a division is the exponent of the dividend less the exponent of the divisor.

(Note: scale = -exponent.)

In your example, both scales are 2, and 2 - 2 = 0. So, the resulting scale is 0. Should you change the divisor to "3", the resulting scale would be 2 because 2 - 0 = 2.

Is there a reason you need to keep the scale at 2? Mathematically it will be correct and you can edit how you display results using fmt.Formatter (via fmt.Sprintf).

**Comment by shannoncolavita** [comment]
Thanks for the response Eric. I thought by using the Go operating mode the scale wouldnt be lost.  We want to keep the scale for display and consistency purposes,  so I will just format it.

**Comment by ericlagergren** [comment]
Ah, yeah. The differences between the modes can be found here: https://godoc.org/github.com/ericlagergren/decimal/#OperatingMode

Sorry for any confusion!

**Comment by ericlagergren** [comment]
Hi @shannoncolavita is it okay if I close this now?

**Comment by shannoncolavita** [comment]
Yes go ahead,  thank you
