### ISSUE TITLE
Howto parse JSON into struct with *decimal.Big?

### ISSUE THREAD

**Issue by Dexus** [ericlagergren/decimal#109]
Hi my problem is that I have a JSON that has normal floats, but I want to use them as `*decimal.Big` in the structure.

How do I do this correctly? I can't find the correct solution at the moment :-( Maybe I'm just blind from the code.

**Comment by ericlagergren** [comment]
The `encoding/json` package only calls `UnmarshalText` if it’s a quoted string. I’ll look into adding support for JSON’s number type.

**Comment by ericlagergren** [comment]
Do you only need unmarshaling or both unmarshaling _and_ marshaling? I think I can do the former, but not the latter.

The reason is that it's trivial to detect whether we're passed a string `"3.1415"` or a number `3.1415`.

```
func (z *Big) UnmarshalJSON(data []byte) error {
    if len(data) >= 2 && data[0] == '"' && data[len(data)-1] == '"' {
        data = data[1:len(data)-1]
    }
    return z.UnmarshalText(data)
}
```

However, I'm hesitant to _marshal_ a decimal as a float because it's inherently lossy. And there's no way for me to provide both the string and float options within the constraints of the encoding/json package. (Configuration options on the Context type are out of the question.)

While Go is nice in that you can easily parse the raw JSON data, other languages aren't. I'd hate to force Go servers to only be able to produce lossy data to their front ends or other systems.

**Comment by Dexus** [comment]
I only need the Unmarshaling first, but I think it would be nice to have it if the Marshaling is also available. But if you value marshaling, you can do it as a float, maybe you can add an "option" (global?) to switch between marshaling as a float or string.

BR, Josef

**Comment by ericlagergren** [comment]
I'll leave it at unmarshaling for now.

If somebody needs to marshal as a JSON number they can implement it themselves via json.Number or a custom type that implements json.Marshaler. It should be pretty easy:

```
type T struct { v *decimal.Big }
func (t *T) MarshalJSON() ([]byte, error) { return t.v.MarshalText() }
```

FWIW: I don't want formatting configuration options in Context because Context should really only be about numerical operations. (That it currently affects very basic string formatting is unfortunate, but unavoidable.) Global options are a no go, since they'd limit the library's ability to run concurrently.
