### ISSUE TITLE
document that SetFloat sets exactly x

### ISSUE THREAD

**Issue by yellowred** [ericlagergren/decimal#122]
Code:
```
package main

import (
	"log"
	"math/big"

	"github.com/ericlagergren/decimal"
)

func main() {
	big := big.NewFloat(0.00805713)
	log.Println(big)
	value := new(decimal.Big).SetFloat(big)
	log.Println(value.String())
}
```

Output:
```
2019/03/28 12:34:12 0.00805713
2019/03/28 12:34:12 0.0080571299999999991536814292203416698612272739410400390625
```

Expected:
the numbers to be the same.

**Comment by ericlagergren** [comment]
This is the expected behavior. I think the only change to be made here is to add the word "exactly" to the SetFloat docs, just like SetFloat64.

Explanation:

Base 2 numbers can't accurately represent all base 10 (decimal) numbers, so `0.00805713` is actually `0.0080571299999999991536814292203416698612272739410400390625...`.

For example:

```
$ cat x.go
package main

import (
	"fmt"
	"math/big"

	"github.com/ericlagergren/decimal"
)

func main() {
	const f = 0.00805713
	big := big.NewFloat(f)
	fmt.Println(big)
	fmt.Printf("%0.58f\n", f)
	value := new(decimal.Big).SetFloat(big)
	fmt.Println(value.String())
	value = new(decimal.Big).SetFloat64(f)
	fmt.Println(value.String())
}
0:1 /tmp $ go run x.go
0.00805713
0.0080571299999999991536814292203416698612272739410400390625
0.0080571299999999991536814292203416698612272739410400390625
0.0080571299999999991536814292203416698612272739410400390625
```

**Comment by yellowred** [comment]
hmm guess I was expecting the lib to handle numbers precisely, as it is supposed to be the add value on top of float64

**Comment by ericlagergren** [comment]
That's the thing. It *is* precise. 

It is precise because, as a base-2 floating point number, `0.00805713` is *the same thing* as `0.0080571299999999991536814292203416698612272739410400390625`.

A good way to demonstrate this is with `big.Rat`. Because it represents numbers as a fraction, it is exact (as fractions always are).

```
r := new(big.Rat).SetFloat64(0.00805713)
// prints 2322309610603241/288230376151711744, which equals
// 0.0080571299999999991536814292203416698612272739410400390625
fmt.Println(r.String())

r, _ = new(big.Rat).SetString("0.00805713")
// prints 805713/100000000, which equals
// 0.00805713
fmt.Println(r.String())
```

**Comment by ericlagergren** [comment]
What you're looking for is `SetFloat` or `SetFloat64` to round its input *from* `0.0080571299999999991536814292203416698612272739410400390625` *to* `0.00805713`.

Unfortunately, that's not really possible without knowing the desired decimal precision ahead of time. Plus, the conversion routines would be complex and possibly expensive.
