### ISSUE TITLE
Using decimal.Big as a map key

### ISSUE THREAD

**Issue by susuper** [ericlagergren/decimal#130]
Hello.
I would like to use decimal.Big as a map key. At the moment it seems to be impossible. Is there any work-around to allow decimal.Big to be a map key?

**Comment by ericlagergren** [comment]
I would convert the decimal to a string and store that. You might have to adjust for differing scales. E.g., 4*10^1 vs 40*10^0. Off the top of my head, you can achieve this via `(*decimal.Big).Set` and some pre-defined `Context`.

For reference: at the moment, slices can't be used as map keys and `decimal.Big` contains slices by virtue of using `big.Int`. Pointers _can_ be used in maps, but Go implements equality by comparing the pointers, not the type behind it. And, at any rate, you likely wouldn't want to compare `decimal.Bigs` using `==` because even if `(*decimal.Big).Cmp` returns zero, the structs might have different memory layouts (e.g., scales like previously mentioned).

Further, there's no way to define custom equality for a map (e.g., `(*T).Equal(T) bool` or `(*T).Cmp(t) int`).

**Comment by susuper** [comment]
Thank you for detailed explanation and for the great decimal library!
