### ISSUE TITLE
SetFloat64 gives somewhat insane result

### ISSUE THREAD

**Issue by aarondl** [ericlagergren/decimal#142]
Hi Eric, while implementing the solution to 404 I ran into this in my test, it seems fairly concerning:

```go
package main

import (
	"fmt"

	"github.com/ericlagergren/decimal"
)

func main() {
	fmt.Println(new(decimal.Big).SetFloat64(54.45))
}
```

Output:

```text
54.4500000000000028421709430404007434844970703125
```

This is on commit: 2c3e3e1 (GOPATH mode).

**Comment by aarondl** [comment]
I verified this on v3.3.1 as well.

**Comment by ericlagergren** [comment]
This is correct behavior. `SetFloat` sets `z` to *exactly* `x`. 

Because base-2 floating point numbers cannot represent all numbers, `x` isn't *just* `54.45`: https://play.golang.org/p/AfYwG79letc

Other packages [1] [2] work around this by converting the input to a string, then converting the string to a decimal.

IMO, the user of the package should be allowed to decide whether or not they want to incur that overhead.

I'm not opposed to adding a new API that does some sort of string conversion. E.g., `decimal/misc.SetRoundedFloat64` or something.

[1]: https://github.com/cockroachdb/apd/blob/5843f9b6a583616d973658cc1f49856dd62b9474/decimal.go#L241
[2]: https://github.com/shopspring/decimal/blob/f1972eb1d1f519e2e5f4b51f2dea765e8c93a130/decimal.go#L211

**Comment by aarondl** [comment]
That's fine. As long as its expected behavior.

As for additional methods for the overhead I'd first ask the question: What would most users of this package expect `SetFloat64()` to do? What it does, or what I expected it would do?

My point in asking the question being that `SetFloat64()` should be the thing that most users wouldn't be surprised by (as many laymen - myself included use it) but that a second function should exist if you need more performance. Rather than the other way around. Of course there's problems with API compatibility now so it's a moot point, but I thought I'd put the thought out there.

Thanks for the response!

**Comment by ericlagergren** [comment]
> What would most users of this package expect SetFloat64() to do? What it does, or what I expected it would do?

Honestly, probably the former. Originally, that's how I implemented it. But I changed it soon after because (1) the overhead was significant, and (2) the Go stdlib's implementations of `(*T).SetFloat64` implement the _latter_. Even though I've my share of complaints with `math/big`, I figured most people would be familiar enough with it that it would make it easier to use this package.

I think I'll add make the documentation better so it's less of a stumbling block.

Sorry about the confusion!

**Comment by lotodore** [comment]
Sorry for digging out this old issue, but I've also encountered this "problem".
IMHO, SetRoundedFloat64 and SetRoundedFloat32 would be really helpful. Current `SetString` has multiple return values, which makes code much more verbose than needed. I think in most cases, current `SetFloat64` is not doing what is needed.
Alternatively, "RequireSetString" with single return value would also help. Just for convenience.

Anyway, thanks for the explanations!
