### ISSUE TITLE
Precision on math.Ceil

### ISSUE THREAD

**Issue by nathanhack** [ericlagergren/decimal#161]
I've come across a case that was unexpected.

See the example: https://play.golang.org/p/m06m-0lINTU

During the example I expected the precision in step 4) to be 17.

**Comment by ericlagergren** [comment]
If you use `ctx.Sub(x, x)` the issue goes away.

It's because, by default, decimals created with `new(Big)`, `var x Big`, etc. use a default `Context` with `DefaultPrecision`. And so the result of subtraction is rounded down and loses a digit.

Note that I really encourage using the `Context` methods instead of the decimal methods. E.g., `ctx.Sub(z, x, y)` instead of `z.Sub(x, y)`. Explicit contexts prevent a lot of bugs.

```
func TestIssue161(t *testing.T) {
	x, _ := new(Big).SetString("8522471020662543")
	p, _ := new(Big).SetString(".75")
	one := new(Big).SetFloat64(1)
	ctx := Context{Precision: x.Precision() * 2}
	fmt.Printf("1) x.Context: %v , p:%v , x: %v\n", x.Context, x.Precision(), x)
	ctx.Add(x, x, one)
	fmt.Printf("2) x.Context: %v , p:%v , x: %v\n", x.Context, x.Precision(), x)
	ctx.Quo(x, x, p)
	fmt.Printf("3) x.Context: %v , p:%v , x: %v\n", x.Context, x.Precision(), x)
	ctx.Ceil(x, x)
	fmt.Printf("4) x.Context: %v , p:%v , x: %v\n", x.Context, x.Precision(), x)
	ctx.Sub(x, x, one)
	fmt.Printf("5) x.Context: %v , p:%v , x: %v\n", x.Context, x.Precision(), x)

	expected, _ := new(big.Int).SetString("11363294694216725", 10)
	acutal := x.Int(nil)
	if acutal.Cmp(expected) != 0 {
		fmt.Printf("expected %v\n", expected)
		fmt.Printf("found    %v\n", acutal)
		fmt.Println("x was:", x)
	}

}
```
