### ISSUE TITLE
Possibly not needed functionlity

### ISSUE THREAD

**Issue by kostya-sh** [ericlagergren/decimal#3]
Generally I think that a library should provide only one way of doing something. Also more functionality means more tests, more maintenance effort, more bugs, etc. So I will list methods that I think you can safely remove from this library (they can always be re-added later):
- `GreaterThan`, `GreaterThanEQ`, `LessThan`, `LessThanEQ`, `Equals` - `Cmp` should be enough
- `Binomial`, `Fib`, `MulRange`, `Jacobi`.  This probably should be in another package or just use `big.Int`. And `FizzBuzz` too! ;)
- `Hypot`, `Log`, `Log10`. This probably should be in another package or just use `big.Float`
- `MarshalJSON`, `UnmarshalJSON`. MarshalText/UnmarshalText are already used by `encoding/json`
- `BitLen`. Probably not needed, the documentation is confusing. What are the use cases?
- `Bytes`, `SetBytes` Probably not needed. How is it different from `GobEncode`/`GobDecode`?
- `Ilog10`. Why round before taking log10? What is the use case for this method?
- What is the difference between `Rem` and `Mod`? Maybe just documentation issue
- sql.Scanner and driver.Value implementations are probably not needed. Storing decimals in databases is database specific.

**Comment by ericlagergren** [comment]
> Cmp and friends

Fair enough.

> Binomial, Fib, MulRange, Jacobi

I like these functions/methods -- I think they could be in their own package but they'd need more support. Perhaps if I added trig functions like sin, cos, tan, etc?

> Hypot, Log, Log10

Similar to the above, I think they could be useful. Perhaps if I had a package with various math functions I'd add them...

> JSON

Gone since `encoding/json` calls `MarshalText` if the type implements it. I think those methods were artifacts from when I originally forked this library (and then gutted 99% of it).

> Bytes

Similar to `math/big.Int`'s `Bytes` and `SetBytes` methods.

> Ilog10 rounded

 Ilog10 is the number of digits in the Decimal -- that's all it is. It's basically a faster `ceil(log10(z))` It's fairly useful internally, and I could see it having some use if people need to figure out the length of a decimal (for, say creating a buffer to store it) before actually converting it into a string or something. I know I've had to do it in the past (not with decimals, but for other reasons).

> sql.Scanner and driver.Value

I suppose. Originally I created this so I could use decimal types with lib/pq :smile: 

Right now it just uses the `String` method, which could be stored as text, varchar, or whatever. I dunno. I'm a little on the fence about this one.

**Comment by kostya-sh** [comment]
The main reason I think methods like Binomial or Hypot shouldn't be provided is because Decimal has very limited use case. Mostly accounting calculations. I suspect 99.9% of users of you library won't use these methods. If you need to calculate Binomial it is better to use big.Int (and probably faster). If you need to calculate Sin, Cos, Hypot, etc it is better to use float64 (much faster) or big.Float (probably faster too).

In the end it is up to you if you want to keep them or not. I just think it will be easier to maintain the library with more focused functionality ;)

Of course you should keep FizzBuzz as it is the main selling point of this package! ;)

> BitLen and Bytes

The meaning and purpose of these types is clear for big.Int, however less clear for Decimal (what about non-integer numbers?). Besides it is always possible to use `d.Unscaled().BitLen()` (BTW, it looks like Unscaled method is missing as well). I would remove these methods.

> Ilog10 rounded

Length of decimal is called precision and there is method `Prec()` to get it. I would unexport this method (it can always be added later).

> sql.Scanner and driver.Value

I don't know enough about database/sql/driver to recommend anything to be honest. Most databases support decimal types with precision specified in the schema so there is no reason to use a varchar column to store decimal numbers. As far as I know there is no single on-wire representation of decimal type in different databases. You just need to make sure that implementing sql.Scanner and Value won't make this class incompatible with different databases and drivers.

**Comment by ericlagergren** [comment]
> Length of decimal is called precision and there is method Prec() to get
> it. I would unexport this method (it can always be added later).

I assumed precision was the # of digits after the radix.

I should've read the entire decimal spec before I decided to name things 😉

> SQL

Makes sense!

> various methods

I noticed GCC reimplemented the float library for decimal. Hmmm...

So much code I can write now! 😁

**Comment by kostya-sh** [comment]
> I assumed precision was the # of digits after the radix.

I should admit that this is how I understood it as well before reading the spec ;)

**Comment by ericlagergren** [comment]
Ha! I'll make it my weekend reading to grok the entire spec.

**Comment by ericlagergren** [comment]
The math/ subpackage now exists!
