### ISSUE TITLE
Lint and cyclo errors

### ISSUE THREAD

**Issue by aarondl** [ericlagergren/decimal#52]
Hey there, was just looking at this library as something to include in sqlboiler for decimal support instead of shopspring/decimal (they have some really scary issues still opened). Do you think it'd be a good fit for something like that? Mostly users would be using it for financial dealings. I'm going to file another issue on the lack of marshallers on this project too, I have a feeling that the `encoding/Text*` interfaces don't work for as many things as you might want them to.

As for the issue at hand, there's quite a number of linting errors in the lib:
https://goreportcard.com/report/github.com/ericlagergren/decimal

**Comment by ericlagergren** [comment]
@aarondl hi, sorry for the delay. I was on vacation without cell service :-)

yep! Should work fine. `MarshalText` does the same thing as `String`. There are a variety of options using the `fmt.Formatter` interface. If you want an example for database use, look at `sql/` subpackage. There's a wrapper for PostgreSQL. I'd love to add support for other databases you might have in mind. I only regularly use PG, that's why it's the only one added so far.

**Comment by ericlagergren** [comment]
With respect to the lint warnings, I'm fine with them. Excluding the warnings from `internal/`, most of the warnings have to do with me mimicking `math/big`'s receiver conventions: you'll get the same warnings if you run `go lint` there, too. Thanks for posting about it, though!

**Comment by ericlagergren** [comment]
@aarondl hey man, just wanted to make sure I answered your questions and, if so, whether you're fine with me closing this issue. Cheers.

**Comment by ericlagergren** [comment]
let me know if you have any more questions.
