### ISSUE TITLE
More convenient way to default to Go OperatingMode?

### ISSUE THREAD

**Issue by shabbyrobe** [ericlagergren/decimal#63]
In my application, I need Go OperatingMode to be the default for all calculations. It's very verbose to establish and easy to forget to properly set contexts. Is it possible to add a more convenient way to set the default to be Go?

**Comment by ericlagergren** [comment]
Two questions:

> In my application, I need Go OperatingMode to be the default for all calculations.

I'm curious why. No particular reason, just want to better learn why/how people use this library.

> Is it possible to add a more convenient way to set the default to be Go?

I'm not sure. The only "zero-touch" way that would make the default be `Go` would be setting a global variable (like `var DefaultOperatingMode = Go`) that people could modify inside `init()`. But that'd require me to add more runtime checks. I'm not a fan of globals nor of more runtime checks than necessary.

A common format I use when using this library is

```
var ctx = decimal.Big{
    Precision: 19,
    Traps: ^decimal.Condition(0),
    ...
}

// avg sets z to the average of the list, a.
func avg(z, a ...*decimal.Big) *decimal.Big {
    for _, v := range a {
        ctx.Add(z, z, v)
    }
    var n decimal.Big
    return ctx.Quo(z, z, n.SetUint64(uint64(len(a))))
}
```

Or, alternatively, when I don't want to use the `ctx.Add( ... )` form, I'll do something like

```
func d() *decimal.Big {
    return decimal.WithContext(decimal.Context{OperatingMode: Go})
}
foo := d()
...
```

**Comment by shabbyrobe** [comment]
Yeah that global was my first thought too, then I started thinking through the horror that could unleash. Being able to modify the behaviour of dependencies that rely in the default being GDA could create some really nasty surprises, which is precisely what I'm trying to avoid! :)

So the main reason why I'm favouring the Go operating mode is that it's about 20% faster (and I'm doing about a jillion calculations so that really 20% really helps), and the other reasons are that the docs say that operations are lossless and because I'd prefer my app blow up on NaN.

So I guess the problem I have is that if I forget even once to do `decimal.WithContext(decimal.Context{OperatingMode: Go})`, I've created a subtle condition where precision could be lost or NaNs could slip through, compromising my whole data pipeline potentially without me knowing.

I'm not sure any of this is right, it's just what I gleaned from reading the docs and code and experimenting with the lib.

**Comment by ericlagergren** [comment]
Seems about right. Let me editorialize a bit and see if I can't help make things a bit more clear.

> So the main reason why I'm favouring the Go operating mode is that it's about 20% faster

Generally, yeah. I hope to get rid of that in the future. It's because the GDA mode (which adheres to the GDA specification) rounds the result of every arithmetic operation down to the `Context`'s precision and, unfortunately, division is slow.

> and the other reasons are that the docs say that operations are lossless

Ignoring the operating mode, every arithmetic operation will be lossless provided two things are true:

1. The resulting precision of the operation is lesser than the `Context`'s precision, and
2. The resulting decimal has a terminating fractional expansion.

Switching to the `Go` operating mode ignores <span>#</span>1. This means that only results that don't terminate will "lose" information (you'd have to have an infinitely large computer to hold the result of 1 / 3, for example, since it's 0.33333... repeating infinitely).

> if I forget even once to do decimal.WithContext(decimal.Context{OperatingMode: Go}), I've created a subtle condition where precision could be lost or NaNs could slip through

This is a reason why I added methods to `Context`—if you always commit to using the `ctx.Mul( ... )` form you'll be fine. Other libraries require you to use that form, but I like choices so I added both. :-)

**Comment by ericlagergren** [comment]
hey, just wondering if you're fine with me closing this issue.

**Comment by ericlagergren** [comment]
Feel free to ping me if you've any more questions!

**Comment by shabbyrobe** [comment]
Sorry for not getting back to you sooner, and thank you for the detailed reply. I'll see how I go with the `ctx.Mul()` form. It could well be enough; as long as it's easy to visually identify wrong use and right use, the way is then paved for writing an automated checker. Would you mind if I commented here again if I run into issues?

**Comment by ericlagergren** [comment]
You’re more than welcome to! (Though, if it’s a different question create a separate issue.) My email’s public as well, but I’d kinda prefer to keep things on GitHub if possible so others can benefit from the Q&A.

I like to use the issues as a TODO list of sorts, so I like to close stuff out when I’m finished so I don’t accidentally forget about it.
