### ISSUE TITLE
Quo() returning NaN when using ContextUnlimited

### ISSUE THREAD

**Issue by OpinionatedGeek** [ericlagergren/decimal#81]
Hi,

This is likely a problem with my expectations, but this code shows NaN rather than a concrete result:
```
package main

import (
	"fmt"

	"github.com/ericlagergren/decimal"
)

func main() {
	money := decimal.WithContext(decimal.ContextUnlimited)
	money.SetString("0.00970299")
	price := decimal.WithContext(decimal.ContextUnlimited)
	price.SetString("0.00008957")
	result := decimal.WithContext(decimal.ContextUnlimited)
	result.Quo(money, price)
	fmt.Println("Money:", money, "Price:", price, "Result:", result)
}
```
It prints:
`Money: 0.00970299 Price: 0.00008957 Result: NaN20`

I'd expected `decimal.ContextUnlimited` to handle (many) more decimal places than the other contexts, at the expense of taking additional time for computations. Is that incorrect?

(Also - is there an example code that shows the use of the error handling, context traps and NaN signalling? I'd like to be using these the proper way but I'm not sure what that proper way is yet.)

Many thanks,

Geoff

**Comment by ericlagergren** [comment]
I'd agree that error handling needs some better examples.

Let me know if anything is confusing, I haven't had coffee yet. :-)

You set can traps (using a bitmask) inside the `Context`. These traps will cause the `Err` method to return a non-nil value, should the corresponding condition be set. For example, if you set `Rounded` and `Rounded | Inexact` are set by an operation, if you call `Err` you'll receive a non-nil error whose underlying type is `Condition` and whose value is `Rounded`. Note that a `Context`'s conditions remain set until explicitly cleared by the caller. The library never clears any set bits.

If a `NaN` result is returned from the library functions, it'll likely include a payload. This payload contains metadata about why the `NaN` occurred. If you call the `Payload` method, you'll receive a value of the same name that implements `fmt.Stringer`. In your case, printing it would show `division with unlimited precision has a non-terminating decimal expansion`. In the future I might expand on `Payload`, but right now I just implement the bare minimum (of this optional feature...) from the GDA spec.

In your example, you have two decimals whose quotient is a non-terminating decimal expansion, meaning `a / b` has an infinite fractional part, just like `1 / 3` does. In your case, the repeating expansion is `328569833649659484202299877191023780283577090543708831081835435971865579993301`. Key point: it's impossible to use "unlimited" precision here because it'd require your computer have unlimited memory to store the infinitely-repeating decimal. (In practice, even using a terminating decimal expansion like `12 / 9` with `UnlimitedPrecision` would result in an error if there's a remainder; this is technically a bug, I think, but matches the results of other well-used libraries like Java's `BigDecimal` so it's low priority.)

Generally, I'd caution against `UnlimitedPrecision` since you'll run into issues (like you just did). It requires you to be sure the decimal can fit in your machine's memory. Instead, choose a decent precision for your use-case (I believe most monetary guidelines the US and EU have put out require something like ~20 decimal, ~4 fractional digits of precision) and go from there. Also, I'd recommend using explicit `Contexts`. E.g.,

```
ctx := decimal.Context{ ... }
ctx.Add(z, x, y)
ctx.Sub(z, x, y)
...
```

**Comment by OpinionatedGeek** [comment]
Thanks, that does help but it leaves me with more questions...!

How would I create a Context with 'something like ~20 decimal, ~4 fractional digits of precision'? I can see the Precision property in the Context, but I don't think that's quite what you mean here. (An example of a Context for the US or EU monetary guidelines could be useful.)

I'm particularly interested in working with cryptocurrencies, which will typically go to far more decimal places than regular currencies. Bitcoin regularly works to 8 decimal places - how should I adjust the Precision then to cope with this? (Since USD typically uses 2 decimal places the way Bitcoin uses 8, is it as simple as adding 6 to the Precision used for monetary guidelines?) What would a sensible Context for arithmetic on cryptocurrencies/tokens look like?

Here's my attempt as a starting point:
Context128 = Context{
        Precision:     30,
        RoundingMode:  ToNearestEven,
        OperatingMode: GDA,
        Traps:         ^(Inexact | Rounded | Subnormal),
        MaxScale:      6144,
        MinScale:      -6143,
    }

(It's just the Context128 with the Precision reduced from 34 to 30.) Is that a sensible approach?

Thanks for the info on error traps and explicit contexts - I'll update my code now I know!

**Comment by ericlagergren** [comment]
Unfortunately, there's no easy way to require a result always have `N` fractional digits without manually calling `Quantize`. _Some_ libraries do that, but it's not well-defined according to the GDA spec (and causes bugs since the term "precision" is defined by IEEE, the people who've been writing binary and decimal floating point specs). My guidance would be to use a high enough precision, say 100, and then `Quantize` down to your required number of decimal places. `x.Precision() + x.Scale()` will provide you the length of the coefficient, i.e., what comes before the radix.

**Comment by OpinionatedGeek** [comment]
Thanks - I am very grateful for your help here.

I thought I'd try putting together some code to make sure I understand what you mean. Let's say you have some money as a stake, you buy some token/coin at the openPrice, and sell it at the closePrice. The money you have at the end would be:

`(stake / openPrice) * closePrice`

So, to take your advice, I'd use a precision of 100 during the operations and then Quantize() at the end.

```
package main

import (
	"fmt"

	"github.com/ericlagergren/decimal"
)

func main() {
	context := decimal.Context{
		Precision:     100,
		RoundingMode:  decimal.ToNearestEven,
		OperatingMode: decimal.GDA,
		Traps:         ^(decimal.Inexact | decimal.Rounded | decimal.Subnormal),
		MaxScale:      6144,
		MinScale:      -6143,
	}
	stake := decimal.WithContext(context)
	stake.SetString("0.00970299")
	openPrice := decimal.WithContext(context)
	openPrice.SetString("0.00008957")
	closePrice := decimal.WithContext(context)
	closePrice.SetString("0.0000909")
	intermediate := decimal.WithContext(context)
	context.Mul(intermediate, stake, closePrice)
	result := decimal.WithContext(context)
	context.Quo(result, intermediate, openPrice)
	fmt.Println("Before Quantize:", result)
	fmt.Println("Precision:", result.Precision(), "Scale:", result.Scale())

	context.Quantize(result, 30)
	fmt.Println("Stake:", stake, "Open:", openPrice, "Close:", closePrice, "Result:", result)

	floatResult := (0.00970299 / 0.00008957) * 0.0000909
	fmt.Println("Float64 Result:", floatResult)

	fmt.Println("After Quantize:", result)
	fmt.Println("Precision:", result.Precision(), "Scale:", result.Scale())
}
```
This outputs:
```
Before Quantize: 0.009847066997878754047113989058836664061627777157530423132745338841129842581221391090766997878754047114
Precision: 100 Scale: 102
Stake: 0.00970299 Open: 0.00008957 Close: 0.0000909 Result: 0.009847066997878754047113989059
Float64 Result: 0.009847066997878753
After Quantize: 0.009847066997878754047113989059
Precision: 28 Scale: 30
```
Is that use of `Quantize()` how you meant it should be used?

Also, I'm not clear on what you mean by `Scale()` and `Precision()` giving the length of the coefficient, or how I should be using it.

Many thanks for taking the time to help with these questions!

**Comment by ericlagergren** [comment]
> Is that use of Quantize() how you meant it should be used?

Yeah, `Quantize` trims decimal digits. `Round` trims total precision. Basically. :-)

> Also, I'm not clear on what you mean by Scale() and Precision() giving the length of the coefficient, or how I should be using it.

So, I'm not 100% sure where I was going with that, _but_, generally:

- Length of entire decimal: `x.Precision()`
- Number of fractional digits: `x.Scale()`
- Length of coefficient: `x.Precision() - x.Scale()`

Also, a word of advice: unless you really need to for some reason, don't chop off any precision until you're finished with calculations (or the algorithm calls for it...). There's two reasons:

1. Accuracy: rounding errors suck and can take a while to creep up, and
2. Performance: you probably won't notice it unless it's in a hot loop or something, and definitely not compared to network overhead, but rounding is _slow_ right now. (When I switch to a BCD backend this won't be an issue, but for now rounding is a huge drag.)

**Comment by OpinionatedGeek** [comment]
That is excellent information and very helpful. Many thanks for taking the time to help me here.

**Comment by ericlagergren** [comment]
Of course! Glad you're using the library.
