### ISSUE TITLE
Float64 isn't documented to return different results than big.Rat.Float64

### ISSUE THREAD

**Issue by cakey** [ericlagergren/decimal#88]
Hey,
I'm getting results from the Float64() function that are unexpected to me. I would expect the exactness flags to line up with big.Rat in this case.

Am I misunderstanding something, or is there a bug?

```
	v, _ := new(decimal.Big).SetString("0.1")
	fmt.Printf("%v\n", v)
	fmt.Println(v.Float64())

	v2 := new(decimal.Big)
	v2.Context.Precision = 999999
	v2 = v2.SetFloat64(0.1)
	fmt.Printf("%v\n", v2)
	fmt.Println(v2.Float64())

	t1, _ := new(big.Rat).SetString("0.1")
	fmt.Printf("%v\n", t1)
	fmt.Println(t1.Float64())

	t3 := new(big.Rat).SetFloat64(0.1)
	fmt.Printf("%v\n", t3)
	fmt.Println(t3.Float64())
```

```
0.1
0.1 true

0.1000000000000000055511151231257827021181583404541015625
0.1 false

1/10
0.1 false

3602879701896397/36028797018963968
0.1 true
```

**Comment by ericlagergren** [comment]
Yes and no to it being a bug. The behavior should be better documented, but it's that way by design.

Since the GDA spec doesn't define conversion to a 64-bit float, I went with "exact" meaning

> mantissa < 1<<52 and exponent in [-22, 22]; that is, it can fit exactly into a 64-bit float without rounding either the mantissa or exponent.

This is different than `big.Rat` which defines "exact" as

> a / b having the same decimal representation as the resulting float

(Not quotes, just set that way for clarity's sake.)

The reason is a bit of a cop-out: converting a rational number (two base-2 numbers) into a floating-point number _while_ keeping track of exactness is pretty straightforward. Converting a decimal (one base-10 number plus an exponent) to a floating-point number _while_ keeping track of exactness isn't. 

For example, `strconv` has nearly 700 lines devoted just to an extended-precision floating-point number so it can parse a string into a floating-point number, but even that doesn't keep track of exactness like `big.Rat` does.

I could convert the decimal to a `big.Rat` and make the conversion there, but that's wasteful.

I'll go ahead and document the behavior. I'm down to put it (making it match the output of `big.Rat.Float64`) on my TODO list, but I think it'll be a bit larger undertaking than it seems, at least if the goal is to have as little overhead as possible.

**Comment by ericlagergren** [comment]
Although, to be clear: there aren't any requirements for certain methods to match other `math/big` methods. E.g., `Int64` returns `(int64, bool)` not `(int64, Accuracy)`. The above post was written from the perspective that the `Float64` method _should_ match `big.Rat.Float64`'s behavior. Taking the opposite approach (wherein it need _not_ match its behavior), I'd say 100% without a doubt there's no bug.

**Comment by cakey** [comment]
Appreciate the response! :)

Makes sense if that's the behaviour you were going for - seems like a reasonable tradeoff against code complexity and performance.

However the documentation reads `and a bool indicating whether x can be exactly represented as a float64` - to me that very strongly implies that the float64 that is created is fundamentally the same number as the decimal - that there is 0 precision loss.

The current return signature is `(f float64, exact bool)` perhaps we should use a different word than exact. `fits`? or something? Definitely a note in the documentation emphasizing the difference anyway.

But anyway, this explains why `.SetString("0.1")` returns true. But based on those semantics, I would have thought `.SetFloat64(0.1)` would return true also? Is this due to the conversions between base 2 and base 10 changing how much precision is required internally?

**Comment by ericlagergren** [comment]
Yep. I’ll make a change in the docs. 

`SetFloat64(0.1)` doesn’t return true because it’s inflated. I think the `exact = true` line should be something like `exact = !math.IsInff, 0) && !math.IsNaN(f)`.

I’ll fix that with the doc change.
