### ISSUE TITLE
Request - Chainable Min/Max Functions

### ISSUE THREAD

**Issue by dhannyz** [ericlagergren/decimal#96]
It would be nice to instead of using separate Cmp()'s in conditions, followed by Copy()'s, to have a max and min function that alters the 'self' struct such that  `a.Max(b).Max(c)` would return and set a as the maximum of a,b,c

**Comment by ericlagergren** [comment]
Would something like this work?

```
// Max sets z to the greater of the provided values.
func Max(z *decimal.Big, x ...*decimal.Big) *decimal.Big

[ ... ]

a.Max(a, b, c) // a is the maximum of a, b, and c.
```

That's really what it should've been in the first place. 

For what it's worth, I don't think `Max` will ever make its way out of `misc/` and into the main package, `decimal/`. I want to keep as many methods out of `decimal/` in order to keep the API clean. Right now `Big` has 53 methods which is a _lot_.

**Comment by dhannyz** [comment]
Oh sorry, I didn't even see those functions in misc
Personally I was thinking of something that basically replicated the Cmp() function and instead of returning a int, it returned a pointer, or set the calling pointer's value to the Min/Max result. Rather than just calling Cmp(), checking the return, then setting accordingly with Copy().
My use case is for a high performance find of min/max on only a few decimal inputs.
Btw, massive performance gain using your library over the previous one i was using

**Comment by ericlagergren** [comment]
> Personally I was thinking...

Ah, yeah, then `Min` and `Max` in `misc/` should work.

```
var z, a, b, c *Big // assume these are set
z.Copy(Max(a, b, c))
```

Ideally, the API would be similar to what I posted in my previous comment, but that'd be a breaking change so it'd have to wait until version 4.0.

> Btw, massive performance gain...

Awesome! I'm glad to hear it. If you don't mind me asking, what're you using this library for? I ask this question whenever people create issues because it's cool to see all the unique ideas.

**Comment by dhannyz** [comment]
I'm actually using this for some sensitive financial trading code
So accuracy and speed is quite important ;)

**Comment by ericlagergren** [comment]
@dhannyz that's cool to know, thanks! You're alright if I close this, right?
